#!/bin/bash

# Script to post test results as a comment on GitHub PR
# This script is called by GitHub Actions workflow

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check required environment variables
if [ -z "$GITHUB_TOKEN" ]; then
    echo -e "${RED}Error: GITHUB_TOKEN environment variable is required${NC}"
    exit 1
fi

if [ -z "$GITHUB_REPOSITORY" ]; then
    echo -e "${RED}Error: GITHUB_REPOSITORY environment variable is required${NC}"
    exit 1
fi

if [ -z "$PR_NUMBER" ]; then
    echo -e "${RED}Error: PR_NUMBER environment variable is required${NC}"
    exit 1
fi

# Configuration
RESULTS_FILE="${1:-test-results/test_results_summary.json}"
API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}"

# Function to log messages
log_info() {
    echo -e "${BLUE}[PR-COMMENT]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to generate markdown comment
generate_comment() {
    local summary_file="$1"
    
    if [ ! -f "$summary_file" ]; then
        echo "## 🤖 Android Test Results

❌ **Test results file not found**

Please check the workflow logs for details."
        return
    fi
    
    # Parse JSON summary
    local total_tests=$(jq -r '.summary.total_tests' "$summary_file" 2>/dev/null || echo "0")
    local passed=$(jq -r '.summary.passed' "$summary_file" 2>/dev/null || echo "0")
    local failed=$(jq -r '.summary.failed' "$summary_file" 2>/dev/null || echo "0")
    local skipped=$(jq -r '.summary.skipped // 0' "$summary_file" 2>/dev/null || echo "0")
    local pass_rate=$(jq -r '.summary.pass_rate' "$summary_file" 2>/dev/null || echo "0")
    local duration=$(jq -r '.summary.duration // "N/A"' "$summary_file" 2>/dev/null || echo "N/A")
    
    # Determine status
    local status_icon="✅"
    local status_text="All tests passed!"
    if [ "$failed" -gt 0 ]; then
        status_icon="❌"
        status_text="Some tests failed"
    fi
    
    # Start building comment
    cat <<EOF
## 🤖 Android Test Results

### ${status_icon} ${status_text}

| Metric | Value |
|--------|-------|
| Total Tests | ${total_tests} |
| Passed | ✅ ${passed} |
| Failed | ❌ ${failed} |
| Skipped | ⏭️ ${skipped} |
| Pass Rate | ${pass_rate}% |
| Duration | ${duration}s |
EOF

    # Add test type breakdown if available
    if jq -e '.test_types' "$summary_file" >/dev/null 2>&1; then
        echo -e "\n### Test Breakdown by Type\n"
        echo "| Type | Total | Passed | Failed | Pass Rate |"
        echo "|------|-------|--------|--------|----------|"
        
        jq -r '.test_types | to_entries[] | 
            "| \(.key) | \(.value.total) | \(.value.passed) | \(.value.failed) | \(.value.pass_rate)% |"' \
            "$summary_file" 2>/dev/null || true
    fi
    
    # Add failed test details if any
    if [ "$failed" -gt 0 ] && jq -e '.failed_tests' "$summary_file" >/dev/null 2>&1; then
        echo -e "\n### ❌ Failed Tests\n"
        echo "<details>"
        echo "<summary>Click to expand failed test details</summary>"
        echo ""
        echo '```'
        jq -r '.failed_tests[] | "• \(.name)\n  Error: \(.error)\n"' "$summary_file" 2>/dev/null || true
        echo '```'
        echo "</details>"
    fi
    
    # Add links
    echo -e "\n### 📎 Artifacts\n"
    echo "- [📊 Full Test Report](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})"
    echo "- [📸 Screenshots](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}#artifacts) (if any failures)"
    echo "- [📝 Logs](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}#artifacts)"
    
    # Footer
    echo -e "\n---"
    echo "*Generated by Android Tests workflow run [#${GITHUB_RUN_NUMBER}](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})*"
}

# Function to post comment
post_comment() {
    local comment_body="$1"
    
    log_info "Posting comment to PR #${PR_NUMBER}..."
    
    # Escape the comment body for JSON
    local escaped_body=$(echo "$comment_body" | jq -Rs .)
    
    # Check for existing comment
    local existing_comment_id=$(curl -s \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Accept: application/vnd.github.v3+json" \
        "${API_URL}/issues/${PR_NUMBER}/comments" | \
        jq -r '.[] | select(.body | contains("🤖 Android Test Results")) | .id' | head -1)
    
    if [ -n "$existing_comment_id" ]; then
        # Update existing comment
        log_info "Updating existing comment (ID: ${existing_comment_id})..."
        
        curl -s -X PATCH \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            "${API_URL}/issues/comments/${existing_comment_id}" \
            -d "{\"body\": ${escaped_body}}" > /dev/null
            
        log_success "Comment updated successfully!"
    else
        # Create new comment
        log_info "Creating new comment..."
        
        curl -s -X POST \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            "${API_URL}/issues/${PR_NUMBER}/comments" \
            -d "{\"body\": ${escaped_body}}" > /dev/null
            
        log_success "Comment posted successfully!"
    fi
}

# Main execution
main() {
    log_info "Starting PR comment generation..."
    log_info "Repository: ${GITHUB_REPOSITORY}"
    log_info "PR Number: ${PR_NUMBER}"
    log_info "Results file: ${RESULTS_FILE}"
    
    # Generate comment
    local comment_body=$(generate_comment "$RESULTS_FILE")
    
    # Post comment
    post_comment "$comment_body"
    
    log_success "PR comment process completed!"
}

# Run main function
main "$@"