#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting
npm run lint

# Run type checking
npm run type-check

# Run prettier check
npm run format:check

# Run tests
npm run test -- --passWithNoTests
